server.port=8085

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/springbootdb_dev

#info
info.project.env=dev

spring.security.user.name=tom
spring.security.user.password=jerry