spring.application.name=SecondSpringBootProject
spring.profiles.active=local


# PostgreSQL Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.username=root
spring.datasource.password=root

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Logging Levels
logging.level.root=INFO
logging.level.com.itp=DEBUG

# Console Log Pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Save logs into file
logging.file.name=logs/application.log

#Actuator Endpoints
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
management.endpoints.web.base-path=/itp/flipkart

#info
info.project.name=Flipkart Ecommerce
info.project.team=ITP
info.project.instructor.name=Umar Solanki
info.project.instructor.contact=+91 8237307111
info.project.instructor.email=umar.solanki@amazon.com

spring.security.user.name=tom
spring.security.user.password=jerry
